Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
>>> 
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
20
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
20
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 8, in <module>
    print(lista[3])
NameError: name 'lista' is not defined
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 6, in <module>
    print(lista1[3])
IndexError: list index out of range
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Ez a vége
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 5, in <module>
    lista.append("Martin")
NameError: name 'lista' is not defined
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 5, in <module>
    lista.append:("Martin")
NameError: name 'lista' is not defined
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 5, in <module>
    lista.append("Martin")
NameError: name 'lista' is not defined
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
>>> 
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 5, in <module>
    lista.append("Martin")
NameError: name 'lista' is not defined
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége

>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 20, in <module>
    szam
NameError: name 'szam' is not defined
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Kérek  egy számotr
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 20, in <module>
    szam = int(input("Kérek  egy számot"))
ValueError: invalid literal for int() with base 10: 'r'
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Kérek  egy számot2
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Kérek  egy számot
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás.
Ez a vége
Kérek  egy számot
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás.
Ez a vége
Kérek  egy számot3
3
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
>>> 
Martin
sikeres lefutás.
Ez a vége
Kérek  egy számot3
3
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás.
Ez a vége
Kérek  egy számot:4
4
>>> 
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
>>> 
Martina
sikeres lefutás.
Ez a vége
Kérek  egy számot:anyád
Traceback (most recent call last):
  File "H:/Git hub feladatok/Pyton/hibakezeles.py", line 27, in <module>
    print(szam)
NameError: name 'szam' is not defined
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás.
Ez a vége
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás
Ez a vége
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás
Ez a vége
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás
Ez a vége
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás
Ez a vége
Kérek  egy számot:2
2
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás
Ez a vége
Kérek  egy számot:da
Kérek  egy számot:fg
Kérek  egy számot:gr
Kérek  egy számot:hz
Kérek  egy számot:gr
Kérek  egy számot:g
Kérek  egy számot:
Kérek  egy számot:3
3
>>> 
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
Martin
sikeres lefutás
Ez a vége
Kérek  egy számot:s
Ez nem szam
Kérek  egy számot:w
Ez nem szam
Kérek  egy számot:r
Ez nem szam
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Kérek  egy számot:
============= RESTART: H:/Git hub feladatok/Pyton/hibakezeles.py =============
valami nem jó
Ez a vége
Kérek  egy számot:
